# Generated by Django 2.2.6 on 2019-10-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('measurement', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdt', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('hsn_code', models.CharField(max_length=120, null=True)),
                ('hsn_group', models.CharField(max_length=120, null=True)),
                ('item_name', models.CharField(max_length=120, null=True)),
                ('mrp', models.CharField(max_length=12, null=True)),
                ('wholesale', models.CharField(max_length=12, null=True)),
                ('sp', models.CharField(max_length=12, null=True)),
                ('retail', models.CharField(max_length=12, null=True)),
                ('branch', models.CharField(max_length=12, null=True)),
                ('loading_charge', models.CharField(max_length=12, null=True)),
                ('is_active', models.IntegerField()),
                ('common_name', models.CharField(max_length=12, null=True)),
                ('reorder_level', models.IntegerField(null=True)),
                ('rack', models.CharField(max_length=12, null=True)),
                ('max_order_level', models.CharField(max_length=12, null=True)),
                ('tax_group', models.CharField(max_length=12, null=True)),
                ('tax_schedule', models.CharField(max_length=12, null=True)),
                ('gst', models.CharField(max_length=12, null=True)),
                ('sgst', models.CharField(max_length=12, null=True)),
                ('igst', models.CharField(max_length=12, null=True)),
                ('cgst', models.CharField(max_length=12, null=True)),
                ('cess', models.CharField(max_length=12, null=True)),
                ('additional_cess', models.CharField(max_length=12, null=True)),
                ('second_name', models.CharField(max_length=12, null=True)),
                ('category', models.ManyToManyField(to='product.Categories')),
                ('manufaturer', models.ManyToManyField(to='product.Companies')),
                ('subcategory', models.ManyToManyField(to='product.SubCategories')),
                ('unit', models.ManyToManyField(to='product.Units')),
            ],
        ),
    ]
