# Generated by Django 2.2.6 on 2019-10-22 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.RemoveField(
            model_name='products',
            name='manufaturer',
        ),
        migrations.RemoveField(
            model_name='products',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='products',
            name='unit',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Companies',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='SubCategories',
        ),
        migrations.DeleteModel(
            name='Units',
        ),
    ]
